package view;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

import controller.AdminController;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author adkm2
 */
public class AdminForm extends javax.swing.JFrame {
    private AdminController adminController = new AdminController();

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Library Manager[Admin]");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        adminController.loadUsersToTable(userTable);

        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
        TableColumn userIdColumn = userTable.getColumnModel().getColumn(0); // Column 0 is userID
        userIdColumn.setCellRenderer(leftRenderer);
        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        signOutLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        getBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        userIDTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        passTF = new javax.swing.JTextField();
        userTypeTF = new javax.swing.JTextField();
        listUsers = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        listLabel.setText("List of Users:");

        userIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        userIDLabel.setText("User ID:");

        passLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        passLabel.setText("Password:");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usernameLabel.setText("Username:");

        userTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        userTypeLabel.setText("User Type:");

        signOutLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        signOutLabel.setText("Sign Out");
        signOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutLabelMouseClicked(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        getBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getBtn.setText("Get by ID");
        getBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deleteBtn.setText("Delete by ID");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        userIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDTFActionPerformed(evt);
            }
        });

        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        passTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTFActionPerformed(evt);
            }
        });

        userTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeTFActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "UserType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listUsers.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passTF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(usernameLabel)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userTypeTF)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cancelBtn)
                            .addGap(35, 35, 35)
                            .addComponent(saveBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(getBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(signOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(listUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTypeLabel))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(getBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signOutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listUsers)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        userIDTF.setText("");
        usernameTF.setText("");
        passTF.setText("");
        userTypeTF.setText("");

        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(false);
        addBtn.setEnabled(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void signOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_signOutLabelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String username = usernameTF.getText();
        String password = passTF.getText();
        int userType = Integer.parseInt(userTypeTF.getText());
        adminController.addUser(username, password, userType);
        adminController.loadUsersToTable(userTable);
        cancelBtn.doClick();
    }// GEN-LAST:event_addBtnActionPerformed
    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        userIDTF.setEditable(true);
        int userId = Integer.parseInt(userIDTF.getText());
        adminController.deleteUser(userId);
        adminController.loadUsersToTable(userTable);
        cancelBtn.doClick();
    }// GEN-LAST:event_deleteBtnActionPerformed

    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getBtnActionPerformed
        // TODO add your handling code here:
        addBtn.setEnabled(false);
        try {
        int userId = Integer.parseInt(userIDTF.getText()); // Lấy UserID từ TextField
        User user = adminController.getUserById(userId); // Gọi controller để lấy thông tin người dùng
        if (user != null) {
            usernameTF.setText(user.getUsername());
            passTF.setText(user.getPassword());
            userTypeTF.setText(String.valueOf(user.getUserType()));
            usernameTF.setEditable(true);
            passTF.setEditable(true);
            userTypeTF.setEditable(true);
            deleteBtn.setEnabled(true);
            saveBtn.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "User not found!");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid User ID!");
    }
    }// GEN-LAST:event_getBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveBtnActionPerformed
        try {
            int userId = Integer.parseInt(userIDTF.getText()); // Lấy UserID từ TextField
            String username = usernameTF.getText();
            String password = passTF.getText();
            int userType = Integer.parseInt(userTypeTF.getText());

            // Gọi phương thức updateUser với userId
            adminController.updateUser(userId, username, password, userType);

            // Tải lại bảng sau khi cập nhật
            adminController.loadUsersToTable(userTable);

            // Đặt lại form về trạng thái ban đầu
            cancelBtn.doClick();
        } catch (NumberFormatException e) {

        }
    }

    private void userIDTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userIDTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userIDTFActionPerformed

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_usernameTFActionPerformed

    private void passTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passTFActionPerformed

    private void userTypeTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userTypeTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userTypeTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton getBtn;
    private javax.swing.JLabel listLabel;
    private javax.swing.JScrollPane listUsers;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel signOutLabel;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField userIDTF;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel userTypeLabel;
    private javax.swing.JTextField userTypeTF;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
