/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author adkm2
 */
public class FilterForm extends javax.swing.JFrame {

    /**
     * Creates new form FilterForm
     */
    public FilterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fictionCB = new javax.swing.JCheckBox();
        dystopianCB = new javax.swing.JCheckBox();
        fantasyCB = new javax.swing.JCheckBox();
        scificCB = new javax.swing.JCheckBox();
        techCB = new javax.swing.JCheckBox();
        horrorCB = new javax.swing.JCheckBox();
        genreLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        authorTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fictionCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fictionCB.setText("Fiction");
        fictionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fictionCBActionPerformed(evt);
            }
        });

        dystopianCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dystopianCB.setText("Dystopian");

        fantasyCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fantasyCB.setText("Fantasy");

        scificCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scificCB.setText("Science Fic");

        techCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        techCB.setText("Tech");

        horrorCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        horrorCB.setText("Horror");

        genreLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        genreLabel.setText("Genre:");

        authorLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authorLabel.setText("Author:");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Title:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fantasyCB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dystopianCB)
                            .addComponent(fictionCB, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horrorCB)
                            .addComponent(scificCB)
                            .addComponent(techCB)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(authorLabel)
                        .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(titleLabel)
                        .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(authorLabel)
                .addGap(18, 18, 18)
                .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(genreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fictionCB)
                    .addComponent(horrorCB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dystopianCB)
                    .addComponent(scificCB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fantasyCB)
                    .addComponent(techCB))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fictionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fictionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fictionCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTF;
    private javax.swing.JCheckBox dystopianCB;
    private javax.swing.JCheckBox fantasyCB;
    private javax.swing.JCheckBox fictionCB;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JCheckBox horrorCB;
    private javax.swing.JCheckBox scificCB;
    private javax.swing.JCheckBox techCB;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
