/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LibrarianController;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Book;

/**
 *
 * @author adkm2
 */
public class LibrarianForm extends javax.swing.JFrame {

    private LibrarianController librarianController = new LibrarianController();

    /**
     * Creates new form LibrarianForm
     */
    public LibrarianForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Library Manager");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        librarianController.loadBooksToTable(bookTable); // Load books into the table
        customizeTableColumns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookList = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        signOutLabel = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        ebookBtn = new javax.swing.JButton();
        listLabel = new javax.swing.JLabel();
        filterBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        manageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Genre", "ISBN", "Available", "Pages", "File Format"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookList.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            bookTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            bookTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            bookTable.getColumnModel().getColumn(5).setPreferredWidth(40);
            bookTable.getColumnModel().getColumn(6).setPreferredWidth(40);
            bookTable.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        signOutLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        signOutLabel.setText("Sign Out");
        signOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutLabelMouseClicked(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        printBtn.setText("Printed Books");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        ebookBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ebookBtn.setText("EBooks");
        ebookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebookBtnActionPerformed(evt);
            }
        });

        listLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        listLabel.setForeground(new java.awt.Color(204, 204, 204));
        listLabel.setText("List:");

        filterBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        filterBtn.setText("Filter");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        manageBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        manageBtn.setText("Manipulate Book");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filterBtn)
                        .addGap(52, 52, 52)
                        .addComponent(cancelBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(bookList, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ebookBtn)
                .addGap(95, 95, 95)
                .addComponent(manageBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listLabel)
                    .addComponent(signOutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn)
                    .addComponent(ebookBtn)
                    .addComponent(manageBtn))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterBtn)
                    .addComponent(cancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookList, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ebookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebookBtnActionPerformed
        // TODO add your handling code here:
        librarianController.loadBooksByTypeToTable(bookTable, true);
    }//GEN-LAST:event_ebookBtnActionPerformed

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
        ManageBookForm manageBookForm = new ManageBookForm(this);
        manageBookForm.setVisible(true);
    }//GEN-LAST:event_manageBtnActionPerformed

    private void signOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_signOutLabelMouseClicked

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        librarianController.loadBooksByTypeToTable(bookTable, false);
    }//GEN-LAST:event_printBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        librarianController.loadBooksToTable(bookTable);
        
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        // TODO add your handling code here:
        FilterForm f = new FilterForm(this);
        f.setVisible(true);
    }//GEN-LAST:event_filterBtnActionPerformed

    public void reloadBookTable() {
        LibrarianController librarianController = new LibrarianController();
        librarianController.loadBooksToTable(bookTable);
    }
    
    public void updateBookTable(List<Book> books) {
        DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng
        for (Book book : books) {
            model.addRow(new Object[]{
                    book.getBookID(),
                    book.getTitle(),
                    book.getAuthor(),
                    book.getGenre(),
                    book.getIsbn(),
                    book.getAvailable(),
                    book.isBookType() ? "eBook" : "Printed",
                    book.getNumberOfPages(),
                    book.getFileFormat()
            });
        }
    }
    
    private void customizeTableColumns() {
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);

        // Căn lề trái cho cột ID
        bookTable.getColumnModel().getColumn(0).setCellRenderer(leftRenderer); // Column 0: ID

        // Căn lề phải cho các cột Available, Pages, File Format
        bookTable.getColumnModel().getColumn(5).setCellRenderer(rightRenderer); // Column 5: Available
        bookTable.getColumnModel().getColumn(6).setCellRenderer(rightRenderer); // Column 7: Pages
        bookTable.getColumnModel().getColumn(7).setCellRenderer(rightRenderer); // Column 8: File Format
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bookList;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton ebookBtn;
    private javax.swing.JButton filterBtn;
    private javax.swing.JLabel listLabel;
    private javax.swing.JButton manageBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel signOutLabel;
    // End of variables declaration//GEN-END:variables
}
