/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author adkm2
 */
public class ReaderForm extends javax.swing.JFrame {

    /**
     * Creates new form ReaderForm
     */
    public ReaderForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookList = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        signOutLabel = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        ebookBtn = new javax.swing.JButton();
        borrowBtn = new javax.swing.JButton();
        listLabel = new javax.swing.JLabel();
        borrowLabel = new javax.swing.JLabel();
        filterBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Genre", "ISBN", "Available", "Pages", "File Format"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookList.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            bookTable.getColumnModel().getColumn(1).setResizable(false);
            bookTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            bookTable.getColumnModel().getColumn(2).setResizable(false);
            bookTable.getColumnModel().getColumn(3).setResizable(false);
            bookTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            bookTable.getColumnModel().getColumn(5).setPreferredWidth(40);
            bookTable.getColumnModel().getColumn(6).setPreferredWidth(40);
            bookTable.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        signOutLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        signOutLabel.setText("Sign Out");

        printBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        printBtn.setText("Printed Books");

        ebookBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ebookBtn.setText("EBooks");
        ebookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebookBtnActionPerformed(evt);
            }
        });

        borrowBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        borrowBtn.setText("Borrow/Download");

        listLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        listLabel.setForeground(new java.awt.Color(204, 204, 204));
        listLabel.setText("List:");

        borrowLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        borrowLabel.setForeground(new java.awt.Color(204, 204, 204));
        borrowLabel.setText("Enter Title to:");

        filterBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        filterBtn.setText("Filter");

        returnBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        returnBtn.setText("Borrowed Books");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setText("Return:");

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ebookBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filterBtn)
                        .addGap(52, 52, 52)
                        .addComponent(cancelBtn)))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrowBtn)
                    .addComponent(borrowLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnBtn)
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(bookList)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listLabel)
                    .addComponent(borrowLabel)
                    .addComponent(signOutLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn)
                    .addComponent(ebookBtn)
                    .addComponent(borrowBtn)
                    .addComponent(returnBtn))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterBtn)
                    .addComponent(cancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookList, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ebookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebookBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bookList;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton borrowBtn;
    private javax.swing.JLabel borrowLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton ebookBtn;
    private javax.swing.JButton filterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel listLabel;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel signOutLabel;
    // End of variables declaration//GEN-END:variables
}
